### ISSUE TITLE
SQLLite Database connectivity issue

### ISSUE THREAD

**Issue by hims1911** [blackbird71SR/Automatic-Attendance-System#1]
[33, 67, 1, 5, 39, 47, 16, 19]
INSERT INTO IT301 (Date,13,16,19,33,39,47,61,67,70,1) VALUES (20171018,A,P,P,P,P,P,A,P,A,P);
Traceback (most recent call last):
File "/home/paran01d/Automatic-Attendance-System/attendance_window.py", line 71, in record_and_mark
self.mark()
File "/home/paran01d/Automatic-Attendance-System/attendance_window.py", line 80, in mark
self.match() #match extracted faces to those in database and update the database
File "/home/paran01d/Automatic-Attendance-System/attendance_window.py", line 202, in match
c.execute(query)

**Comment by hims1911** [comment]
[33, 67, 1, 5, 39, 47, 16, 19]
INSERT INTO IT301 (Date,13,16,19,33,39,47,61,67,70,1) VALUES (20171018,A,P,P,P,P,P,A,P,A,P);
Traceback (most recent call last):
  File "/home/paran01d/Automatic-Attendance-System/attendance_window.py", line 71, in record_and_mark
    self.mark()
  File "/home/paran01d/Automatic-Attendance-System/attendance_window.py", line 80, in mark
    self.match() #match extracted faces to those in database and update the database
  File "/home/paran01d/Automatic-Attendance-System/attendance_window.py", line 202, in match
    c.execute(query)

**Comment by huylevuanh** [comment]
Have you solved this problem yet?

**Comment by blackbird71SR** [comment]
Really sorry for that one!  Here is the solution:

When I am doing join on rolls and temp, instead of giving the stringed values of rolls and temp, it is just outputting normal values.

The query we want is this:
`INSERT INTO IT301 (Date,"1","2","3","4") VALUES (20171018,"P","A","A","P");`
While we are getting
`INSERT INTO IT301 (Date,1,2,3,4) VALUES (20171018,P,A,A,P);`


Here is the simple fix:
Add this two lines before you define query:
```
rolls = ['"' + i + '"' for i in rolls]
temp = ['"' + i + '"' for i in temp]
```

Let me know if it works for you, so that I can update the repo.
